### ISSUE TITLE
xgboost4j predictleaf 

### ISSUE THREAD

**Issue by joyang1** [criteo-forks/xgboost-jars#2]
why leaf number is always 3? 
does this jar for windows error?

**Comment by superbobry** [comment]
Hi @joyang1, the Windows build is OK to the best of my knowledge. Please forward any problems/issues to the official bug tracker: https://github.com/dmlc/xgboost

**Comment by joyang1** [comment]
@superbobry thx~~ This is my fault. 😂 😂  I solved this problem.
