### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by gilfoyle0213** [criteo-forks/xgboost-jars#3]
could you explain how to use this project ?

**Comment by superbobry** [comment]
You don't need this project unless you want to run the JVM bindings of XGBoost on Windows. Please use official JARs instead: https://mvnrepository.com/artifact/ml.dmlc/xgboost-jvm

@alois-bissuel maybe we want this bit in the README.

**Comment by trams** [comment]
I'll close this issue due to inactivity. Feel free to reopen if you still have questions
